# Generated by Django 4.0.1 on 2022-10-07 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
                ('avtor', models.CharField(max_length=155)),
                ('src', models.FileField(upload_to='media/articles')),
                ('file', models.FileField(upload_to='media/articles')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('src', models.FileField(upload_to='media/books/src')),
                ('date', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='media/books/file')),
                ('avtor', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('src', models.FileField(upload_to='media/documents/src')),
                ('date', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='media/documents/file')),
                ('avtor', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('src', models.FileField(upload_to='media/events/src')),
                ('date', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='media/events/file')),
                ('avtor', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('chat', models.CharField(blank=True, max_length=155, null=True)),
                ('avtor', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('src', models.FileField(upload_to='media/events/src')),
                ('date', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='media/events/file')),
                ('avtor', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='media/videos/file')),
                ('date', models.CharField(max_length=155)),
                ('avtor', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('date', models.CharField(blank=True, max_length=155, null=True)),
                ('user', models.CharField(blank=True, max_length=155, null=True)),
                ('fio', models.CharField(max_length=255)),
                ('group', models.ManyToManyField(to='api.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
