# Generated by Django 4.0.1 on 2022-10-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('src', models.FileField(upload_to='media/courses/src')),
                ('date', models.CharField(max_length=155)),
                ('file', models.FileField(upload_to='media/courses/file')),
                ('avtor', models.CharField(max_length=155)),
                ('content', models.CharField(max_length=155)),
            ],
        ),
    ]
