# Generated by Django 4.0.1 on 2022-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='group_id',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='user_id',
            field=models.CharField(max_length=155),
        ),
    ]
