# Generated by Django 4.0.1 on 2022-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_groupuser_group_id_alter_groupuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
